### ISSUE TITLE
It is currently not possible to close a project

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/elgg-projects#7] opened 2017-11-26 13:53 UTC
~ie /project/view/786743 only site's admin can mark as complete, not the user who created the project/task, lso Task's title is not clickable by normal user~

It's not possible to close a project.

**Comment by juho-jaakkola** [comment] 2017-11-26 14:03
I'm not able to reproduce this bug. Which user were use using when testing?

**Comment by michelesbw** [comment] 2017-11-26 14:07
@michele , tested both on Chrome and FF, issue confirmed

**Comment by juho-jaakkola** [comment] 2017-11-26 14:23
This problem is in fact only with projects, and not with tasks, right?

**Comment by juho-jaakkola** [comment] 2017-11-26 14:33
I logged in with the `michele` user, and in the task I see the button just like I should:

![image](https://user-images.githubusercontent.com/883920/33240923-e37cdf68-d2be-11e7-84b0-587942f22f32.png)

I don't think the assignee of a single task should be able to close the whole project. So that part is working as intended, right?

**Comment by michelesbw** [comment] 2017-11-26 14:36
![screenshot-beta socialbusinessworld org 2017-11-26 15-33-09-358](https://user-images.githubusercontent.com/5203511/33240960-6a8620b4-d2bf-11e7-88eb-f4cf5aa8a1e7.png)

Dunno cause I can't access as normal user so I guess you're right

**Comment by juho-jaakkola** [comment] 2017-11-26 17:31
I updated the issue title to be more accurate.

Do we want to have both options, for closing a project:
 - Manually by project owner
 - Automatically when all tasks are completed

There are pros and cons for both:
- In what case would someone want to close the project manually *before* all the tasks have been completed? Therefore automatic closing would be better once all tasks are completed.
- Someone might finish all existing tasks *before* the project owner has had the chance to enter them all to the project. So perhaps automation should not be implemented at all?

**Comment by juho-jaakkola** [comment] 2017-11-26 17:31
The automation can't really be trusted, so I think it might be best to have only the manual option. The project owner would be responsible for closing the project once all tasks have been completed, and there is no reason to expect any new tasks.

**Comment by juho-jaakkola** [comment] 2017-11-29 17:39
Fixed in f7b9d000c849fc67bed009df77fd3d215f6e4b49

**Closed by juho-jaakkola** 2017-11-29 17:39 UTC
Labels: bug
